function allexamples2d()
    include("arrangement2d.jl")
    include("biconnectedgraphs.jl")
    include("graphalgorithms.jl")
    include("orient2d.jl")
    include("point_in_polygon.jl")
    include("randomarrangement2d.jl")
    include("randombubbles.jl")
    include("randomlines.jl")
    include("randomshapes.jl")
    include("stresstest2d.jl")
    include("svg2lar.jl")
    include("threesquares.jl")
    include("tinypolygons.jl")
    include("triangle.jl")
    include("twoholes.jl")
end

allexamples2d()
